### PR TITLE
Update lec03c.txt

### PR DESCRIPTION
**Pull request by relicwang**
Hi Prof. Robby!

The provement is really clear!  I trying to adjust two words, I am not sure whether I understand the context correctly to make the adjustsment, can you double check?

Thank you!

Relic

### CODE REVIEW

**Comment by relicwang** [comment]
Hi Prof. Robby!

The provement is really clear!  I trying to adjust two words, I am not sure whether I understand the context correctly to make the adjustsment, can you double check?

Thank you!

Relic

**Comment by rfindler** [comment]
I think the edits aren't right. In the first case, the number is supposed to be a natural number (because it is products and sums of natural numbers), which means it is bigger than zero, but the equation says it must be less than -1. 

In the second case, the phrase "if this is to work" means "if it is possible for this to be true".

I've tried to edit the text. See if the new version is clearer?

**Comment by relicwang** [comment]
Yes! It is great for me! Sorry for my bad English!

**Comment by rfindler** [comment]
Thanks for all your help spotting the unclear places. That is the hard part!

**Pull request closed without merging**
